version: '3.7'

services:
  app:
    build:
      context: ./www
      dockerfile: Dockerfile
    container_name: php_app
    image: php_app:${APP_VERSION} 
    ports:
      - "${WEB_PORT}:80"
    volumes:
      - ./www:/var/www/html 
    networks:
      - app_network

  db:
    build:
      context: ./database
      dockerfile: Dockerfile
    container_name: mysql_db
    image: mysql:5.7
    ports:
      - "${DB_PORT}:3306"
    environment:
      MYSQL_ROOT_PASSWORD