services:
  app:
    platform: linux/arm64
    build: ./www
    container_name: php_app
    image: teddyandria/php_app:${APP_VERSION}
    ports:
      - "${WEB_PORT}:80"
    volumes:
      - ./www:/var/www/html 
    environment:
      - DB_NAME=${DB_NAME}
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_PORT=${DB_PORT}

    depends_on:
      - db

  db:
    platform: linux/amd64
    build: ./database
    container_name: mysql_db
    image: teddyandria/mysql:5.7.12

    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
